---
# tasks file for php
- apt: update_cache=yes

# Common configurations to be run on all hosts
# http://www.sitepoint.com/run-multiple-versions-php-one-server/
- name: Install default packages
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - gcc
    - make
    - libc-dev
    - libtool
    - re2c
    - autoconf
    - automake
    - git
  tags:
    - apt
    - php

- name: download file and force basic auth
  get_url: url=http://launchpadlibrarian.net/140087283/libbison-dev_2.7.1.dfsg-1_amd64.deb dest=/opt/
  sudo: yes
  tags:
    - php

- name: download file and force basic auth
  get_url: url=http://launchpadlibrarian.net/140087282/bison_2.7.1.dfsg-1_amd64.deb dest=/opt/
  sudo: yes
  tags:
    - php

- name: Install libbison
  apt: deb=/opt/libbison-dev_2.7.1.dfsg-1_amd64.deb
  sudo: yes
  tags:
    - php

- name: Install bison
  apt: deb=/opt/bison_2.7.1.dfsg-1_amd64.deb
  sudo: yes
  tags:
    - php

- name: Creates directory
  file: path={{item}} state=directory owner=vagrant group=vagrant
  with_items:
    - /opt/source/php-src
  sudo: yes
  tags:
    - php

- name: clone php-src
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=master force=yes
  tags:
    - php

- name: checkout PHP 7.1
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=master clone=no force=yes
  tags:
    - php

- name: build PHP 7.1
  shell: cd /opt/source/php-src; make clean; ./buildconf --force; ./configure --prefix="/usr/local/bin/php-7.1" --with-config-file-path="/usr/local/etc/php-7.1" --enable-mbstring --enable-tokenizer --enable-phar --with-sqlite3 --enable-json --disable-all; make ; make install
  tags:
    - php

- name: php71 symlink
  file: src=/usr/local/bin/php-7.1/bin/php dest=/usr/local/bin/php71 state=link
  tags:
    - php

- name: checkout PHP 7.0
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=php-7.0.0 clone=no force=yes
  tags:
    - php

- name: build PHP 7.0
  shell: cd /opt/source/php-src; make clean; ./buildconf --force; ./configure --prefix="/usr/local/bin/php-7.0" --with-config-file-path="/usr/local/etc/php-7.0" --enable-mbstring --enable-tokenizer --enable-phar --with-sqlite3 --enable-json --disable-all; make ; make install
  tags:
    - php

- name: php70 symlink
  file: src=/usr/local/bin/php-7.0/bin/php dest=/usr/local/bin/php70 state=link
  tags:
    - php

- name: php symlink (for running exakat)
  file: src=/usr/local/bin/php-7.0/bin/php dest=/usr/local/bin/php state=link
  tags:
    - php

- name: checkout PHP 5.6
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=php-5.6.16 clone=no force=yes
  tags:
    - php

- name: build PHP 5.6
  shell: cd /opt/source/php-src; make clean; ./buildconf --force; ./configure --prefix="/usr/local/bin/php-5.6" --with-config-file-path="/usr/local/etc/php-5.6" --enable-mbstring --enable-tokenizer --with-sqlite3 --enable-json --disable-all; make ; make install
  tags:
    - php

- name: php 5.6 symlink
  file: src=/usr/local/bin/php-5.6/bin/php dest=/usr/local/bin/php56 state=link
  tags:
    - php

- name: checkout PHP 5.5
  git: repo=https://github.com/php/php-src.git dest=/opt/source/php-src version=php-5.5.31 clone=no force=yes
  tags:
    - php

- name: build PHP 5.5
  shell: cd /opt/source/php-src; make clean; ./buildconf --force; ./configure --prefix="/usr/local/bin/php-5.5" --with-config-file-path="/usr/local/etc/php-5.5" --enable-mbstring --enable-tokenizer --with-sqlite3 --enable-json --disable-all; make ; make install
  tags:
    - php

- name: php 5.5 symlink
  file: src=/usr/local/bin/php-5.5/bin/php dest=/usr/local/bin/php55 state=link
  tags:
    - php

- name: clean php-src
  shell: rm -rf /opt/source/php-src
  tags:
    - php
